#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Exercise 18: Cows And Bulls

Create a program that will play the “cows and bulls” game with the user.
The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit
number.
For every digit that the user guessed correctly in the correct place,
they have a “cow”. For every digit the user guessed correctly in the
wrong place is a “bull.” Every time the user makes a guess, tell them
how many “cows” and “bulls” they have. Once the user guesses the correct
number, the game is over.
Keep track of the number of guesses the user makes throughout teh game
and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction
could look like this:

    Welcome to the Cows and Bulls Game!
    Enter a number:
    >>> 1234
    2 cows, 0 bulls
    >>> 1256
    1 cow, 1 bull

Until the user guesses the number.
"""

import random


def get_secret_number():
    """ Define the secret number and write it to a file.
    """
    secret_number = str(random.randint(1000, 9999))

    with open("secret_number.txt", "w") as file:
        print(secret_number, file=file)

    return secret_number


def get_cows_and_bulls(secret, user):
    """Calculate the amount of cows and bulls.
    """
    cows = bulls = 0
    secret_chars = secret

    for i in range(len(secret)):
        if user[i] == secret[i]:
            cows += 1
        if user[i] in secret_chars:
            bulls += 1
            secret_chars = remove_char(secret_chars, user[i])

    return cows, bulls


def remove_char(s, c):
    """Remove a char of the string.
    When a user character exist in a secret_chars, add 1 to bulls and
    remove it of secret_chars to don't duplicate the count
    """
    list_chars = list(s)
    list_chars.remove(c)
    return "".join(list_chars)


if __name__ == "__main__":

    guessed = False
    attempts = 0
    secret = get_secret_number()

    while not guessed:
        user = input("Guess a 4-digit number: ")
        attempts += 1

        if user == secret:
            guessed = True

        print("%i cows, %i bulls" % (get_cows_and_bulls(secret, user)))

    print(
        "Congrats! The number is %s. You did %s attempts." %
        (secret, attempts))
